### ISSUE TITLE
Multiple threats.

### ISSUE THREAD

**Issue by o0ster** [jshayes/arma3-chemical-detector#1]
I'm fairly new at scripting but I'm struggling with creating multiple threats in the same instance to be tracked with the script you provided. 
I've tried everything in my knowledge to create more than one but I'm going to sum it up to user error on my part.

Any ideas on how to achieve this goal?

**Comment by jshayes** [comment]
Do you mean tracking multiple threats at the same time? OR do you mean sequentially, once one threat is found, then move on to another threat?

If tracking at the same time, this script doesn't currently work with that. I could look into making it show the reading for the closest threat.

**Comment by o0ster** [comment]
Ah, ok. Yes, I meant for tracking at the same time. That makes sense then. Well thank you for the quick response, I'll be keeping an eye on this one.
